title: "Marie Nguyen"
email: ammynguyen1010@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" 
url: "https://marienguyen20.github.io/" 
twitter_username: MyNguye85318700
github_username:  marienguyen20

sass:
  sass_dir: _sass

icon: ./assets/img/avatar.jpg
